### PR TITLE
Support for MRI 2.4

### PR DESCRIPTION
**Pull request by flash-gordon**
I found dry-initializer has a failing spec on MRI 2.4, I'm going to find out why...

### CODE REVIEW

**Comment by flash-gordon** [comment]
Ok, so
MRI 2.3:
```
$ ruby -e "instance_eval(&lambda { |_| return })"
```
MRI 2.4: 
```
$ ruby -e "instance_eval(&lambda { |_| return })"
-e:1:in `block in <main>': unexpected return (LocalJumpError)
	from -e:1:in `instance_eval'
	from -e:1:in `<main>'
```
I'll file a ticket to bugs.ruby-lang.org, but we can easily fix it for now, I'll commit a workaround

**Comment by flash-gordon** [comment]
https://bugs.ruby-lang.org/issues/13090

**Comment by solnic** [comment]
I guess this can be merged/released?

**Comment by nepalez** [comment]
I think so )))

@flash-gordon thank you!
Sorry man, I'm too busy now with a commertial project, couldn't answer earlier

**Comment by flash-gordon** [comment]
ah, sure, no problem

**Pull request merged**
