### PR TITLE
Refactor config to process arguments by dispatchers

### PR DESCRIPTION
**Pull request by nepalez**
Processing of all the arguments of `.option` and `.param` definitions was extracted to separate dispatchers.

Now we have more control of the processing and can provide additional rules by adding new dispatchers.

This can be used for:
- fixing longstanding issue about too strict arity check for dry-types
- adding support for 'array types' like:
  ```ruby
  option :foo, [method(:String)]
  ```
  as an alternative to
  ```ruby
  option :foo, ->(v) { Array(v).map { |item| String(item) } }
  ```
- adding support for nested struct definitions like:
  ```ruby
  option :foo do
    option :bar
    option :baz
  end
  ```
The downside of this change is that it adds more instantiations of objects (several dispatchers for
every definition). But because this job is done in loading time I count this as not important.

### CODE REVIEW

**Comment by nepalez** [comment]
@timriley @flash-gordon Hi guys!

Could you take a look at this PR? Remembering the summer case I'm a bit scared to break `rom` once again (I hope not, but who knows). It would be nice if you could check that it doesn't.

**Comment by flash-gordon** [comment]
@nepalez I ran tests against this branch and they passed so it should be fine

**Comment by nepalez** [comment]
@flash-gordon Thank you. I'll add support for nested structs and then make a release

**Comment by nepalez** [comment]
Closed due to the wrong name of the version `must be v7.0.0`

**Pull request closed without merging**
