### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by nepalez**
@solnic @flash-gordon please take a look at the top of the [changelog](https://github.com/dry-rb/dry-initializer/blob/2.0.0/CHANGELOG.md).

I'd wait merging this PR until you check that it is rom-compatible (with some minor updates concerning `@__options__` --> `self.class.dry_initializer.attributes(self)`).

### CODE REVIEW

**Comment by flash-gordon** [comment]
@nepalez @solnic I created a PR for this https://github.com/rom-rb/rom/pull/451
We've got a significant performance impact, specs in core are slowed down from 1.4s to around 7.5s on my machine, i.e. 5x. It's obviously for the reason we initialize a lot of objects and most of them are get initialized via copying options with updating a couple of keys. I tried to use memoization but it didn't work well enough, 7.5s dropped down to 5.6s only. It looks like the suggested solution doesn't work optimal but I'm not sure how to make it as performant as it was. We could just reimplement it in `rom` if dry-initializer offered a means for this.

The new release isn't compatible with ruby 2.2, it's not a problem though this version is [still supported](https://www.ruby-lang.org/en/downloads/branches/)

**Comment by flash-gordon** [comment]
oh, there is one spec failing and I have no idea why https://travis-ci.org/rom-rb/rom/jobs/267682460 @nepalez any clues?

**Comment by nepalez** [comment]
@flash-gordon Thank you I'll dig into that cases tomorrow. The falling test is obviously a bug, i'll fix it asap.

Concerning performance, it's very sad news ((
The problem is I cannot figure out why such an impact could occur because I've made minimal additions to the code of the initialize by itself.

For example, that's how processed this declaration:

```ruby
module Test::Types
  include Dry::Types.module
end

class Test::Foo
  extend Dry::Initializer

  param  :foo, type: Test::Types::Coercible::String
  option :bar, proc(&:to_i), default: proc { "16" }
end
```

```ruby
private def initialize(*args)
  __dry_initializer_initialize__(*args)
end

private def __dry_initializer_initialize__(foo, *, **__dry_initializer_options__)
  
  __dry_initializer_definition__ = __dry_initializer_config__.definitions[:'foo']
  foo = __dry_initializer_definition__.type.call(foo) unless foo == Dry::Initializer::UNDEFINED
  @foo = foo unless foo == Dry::Initializer::UNDEFINED && instance_variable_defined?(:@foo)
  
  __dry_initializer_definition__ = __dry_initializer_config__.definitions[:'bar']
  __dry_initializer_value__ = __dry_initializer_options__.fetch(:'bar', Dry::Initializer::UNDEFINED)
  __dry_initializer_value__ = instance_exec(&__dry_initializer_definition__.default) if __dry_initializer_value__ == Dry::Initializer::UNDEFINED
  __dry_initializer_value__ = __dry_initializer_definition__.type.call(__dry_initializer_value__) unless __dry_initializer_value__ == Dry::Initializer::UNDEFINED
  @bar = __dry_initializer_value__ unless __dry_initializer_value__ == Dry::Initializer::UNDEFINED && instance_variable_defined?(:@bar)
end

def foo
  @foo unless @foo == Dry::Initializer::UNDEFINED
end

def bar
  @bar unless @bar == Dry::Initializer::UNDEFINED
end
```

The only slow thing here is evaluation of defaults and types which are "procs" enclosured into instance variable `@__dry_initializer_config__`. But it is exactly the same mechanizm as before.

Well, I need to play with it in a week.

**Comment by nepalez** [comment]
The only reason I can suggest concerns `[undefined: false]` version. On benchmarks I see no difference between this version and default `Dry::Initializer::UNDEFINED` one.

But I remember there **was** an impact on performance before.

**Comment by flash-gordon** [comment]
@nepalez I'll profile the specs tomorrow, it just can be a combination of code evaluation + changed `options`. It's not only about how fast dry-initializer works with existing classes but also how fast it generates a constructor (and I keep forgetting it lol)

**Comment by nepalez** [comment]
Ahh, yes, options can work much slower because instead of

```
@__options__
```

now we have

```
self.class.dry_initializer.attributes self
```

or (another hint I did this evening)

```
@__dry_initializer_config__.attributes self
```

From the other hand, we didn't build `@__options__` during instantiation any more, so I don't think it explains the 3x difference.

---
I've found another place to optimize. I used `default: -> { Dry::Initializer::UNDEFINED }` as a substitute for `optional: true`. It can add some underperformance (about ~60% in the worst case).

**Comment by nepalez** [comment]
@flash-gordon I've changed code for `optional: true` for not to use slow defaults. For now I see no other ways of optimization.

Because rom [pinned dry-initializer to `-> 1.3`](https://github.com/rom-rb/rom/blob/master/core/rom-core.gemspec#L20) I found it safe to release 2.0

**Comment by flash-gordon** [comment]
@nepalez yes, we're not gonna update the dep in the 4.0 release, it's kind of too late. However, we should find out the reasons of performance degradation so that we could bump the dep version in 4.x without obstacles. 
I profiled the specs and 80% of the time in dry-initializer was consumed by `Dry::Initializer::Config#children`
I looked in the [code](https://github.com/dry-rb/dry-initializer/blob/098829f3b72d7060dee3aebc9bb165fae78efd39/lib/dry/initializer/config.rb#L34-L41) and was surprised quite a bit. `ObjectSpace` should never be accessed from libraries that don't do profiling/monitoring, it's a hack. Basically, need for reaching `ObjectSpace` means a missing abstraction. This shouldn't go to master, we need to find another way for what this code does. I could help with this if you tell me its purpose.

**Comment by nepalez** [comment]
D'oh!
That's really interesting, because it is expected the `children` to be invoked at load time only.

Its purpose is the following. Look at two snippets below. In both the cases I'd expect exactly the same definition both for `Foo` and `Bar`. In other words, I'd like the definition not to depend on loading order.

```ruby
class Foo
  extend Dry::Initializer
  param :foo
end

class Bar < Foo
  param :bar
end
```

```ruby
class Foo
  extend Dry::Initializer
end

class Bar < Foo
  param :bar
end

class Foo
  param :foo # <- this should affect Bar as well
end
```

To do this I cannot just use `super` because I need to reflect `foo` parameter in the signature of `Bar#__initialize__`. To do this I skip through all the descendands of the current class and update their code. The method `#children` returns that descendands (to be more accurate, it returns not subclasses, but their containers; whatever).

And yes, you're right! Now it seems realy hacky to me; it would be better to remember `#children` from the `#inherited` method. I'll fix it asap, that's simple.

From the other hand, it is strange that this declaration affect your benchmarks; The method `children` is called by `.param` and `.option` DSL methods. IMO classes should never be reloaded/redefined at the runtime -- this is really, really slow, not to mention such a redefinition is thread-unsafe. tbh, I didn't ever optimize the performance of those declarations.

**Comment by flash-gordon** [comment]
@nepalez ahh, I see, yes tracking descendants with `inherited` is better. I tested the whole suite, i.e. including the load time. There are a couple of dozens of classes get loaded that use dry-initializer but can clearly see how bad it affects the performance, as I said it dropped from about 1.5s to 7.5s or even more.

After pulling the latest changes it went down to something about from 1s to 1.4s which is good 👍  but now I see some errors in rom-repo. It seems that the `undefined: false` doesn't work with inheritance in the new version

```ruby
class Test::Foo
  extend Dry::Initializer[undefined: false]
end

class Test::Bar < Test::Foo
end

Test::Foo.dry_initializer.null => nil
Test::Bar.dry_initializer.null => #<Object:0x007f841c8cca10>
```
should be an easy thing to fix ;)

**Comment by nepalez** [comment]
Yeah, I'll fix it this night ))

Thank you for your help with this issue!

I believe you still should check your benchmarks. It's very strange them to count both a run time (initializer) and load time (params/options -> children) in the same "example". The result of such a profiling could be unpredictable ;)

**Comment by flash-gordon** [comment]
@nepalez ah, thank you :) I didn't run benchmarks for the runtime part, it's just `rspec` execution became clearly slower. Since I didn't know if that happened during the load part or the runtime part, I took `hotch` and profiled both. At this point, it looks like it was enough :) We'll benchmark `rom` later but I don't think dry-initializer will be a problem there

**Pull request merged**
