### PR TITLE
Add refinements support

### PR DESCRIPTION
**Pull request by hrom512**
Rename `#using` to `#with_settings`

### CODE REVIEW

**Comment by nepalez** [comment]
Дякую!

I'll postpone merging the PR for a day, because we need adding deprecation in v0.9.3 first.

**Comment by nepalez** [comment]
In fact, we have another option for the case. Namely, we could just reload root `using` like this:

```ruby
def using(**options)
  return super unless block_given? # reduce to refinement
  # ... do our staff here
end
```

The reason why I'm hesitating with this, is that I dislike the very idea of polluting namespace with new methods. In case of `using` we in a sense "protected" from user to add its own using.

**Comment by hrom512** [comment]
I think it can make the ambiguity in the code. For example:

```ruby
class Foo
  extend Dry::Initializer::Mixin

  using MyRefinement

  using default: proc { nil } do
    param :foo
    param :bar
  end
end
```

Applying `using` in a different contexts is confusing.

**Comment by nepalez** [comment]
@solnic @AMHOL @jeremyf @flash-gordon  what d'you think about the subject?

**Comment by solnic** [comment]
I actually don't like `with_settings`-like API at all. I'm perfectly OK with repeating a couple options few times, my potential use-case for dry-initializer is probably different than yours ie. I want to replace rom-rb's `Option` API with it and I'm not concerned with some duplication of options.

FWIW in some cases you can define a type that can carry common behavior, ie `DefaultProc = Types::Definition.new(Proc).constrained(type: Proc).default(-> v { v })` and then just re-use it in many places.

**Comment by solnic** [comment]
Oh and regarding refinements, I don't like them, they are only a bit better than global monkey-patches, but since `using` is a reserved word then libs shouldn't use it as their own method.

**Comment by nepalez** [comment]
@solnic thank you! Yes, I know about this possibilty. The reason to use `default` in dry-initializer instead of dry-types' `.default` is that you can refer to other arguments like

```ruby
param :foo
param :bar, default: proc { foo.to_s.reverse }
```

And yes, I agree to you about refinements (I even totally forgot about reversed `using` when building that interface). Well, if not `using`, we still should think of better method name (maybe `attributes`?)

Concernint duplication, I'd say this is not only about duplication, but making code more readable. For example, in big structure it makes sense for me to separate optional part of the structure from mandatory one, or separate part without readers etc.

**Comment by marshall-lee** [comment]
In my opinion, both `using` and `with_settings` are bad words for naming this thing. "Using" what? With what "settings"? It's not clear how the words "using" or "settings" are related to the problem of defining a **constructor**. User's classes contain not only our initializer included but maybe something else that could be "used" or something that has "settings". I don't want to conflict with someone other's terminology. Even adding of `param` and `option` methods is bad but I think of it as an 'ultimate trade off' and don't want to add any new methods.

I propose to remove this `using` at all. I'm strictly against of such a bloat in this gem, please just stop adding new features. It's not a place for "rich" DSL, it's not a "value object" or something. `dry-initializer` is aimed to do just **one** simple thing: define a typical ruby **constructor** (aka `initialize` method). "Typical" means something that assigns constructor arguments to instance variables. That's all! If someone wants to build a "value object" on top of it - you're welcome! Just make a base class, include `Dry::Initializer` to it and override `param` method to implicitely include `default: proc { nil }` everywhere. You can even rename it to `attribute` or whatever you want. 

I don't think that every "good open source project" should evolve by constantly adding new features. In case of `dry-initializer` it's not an evolution, it's just a bloat. True evolution of `dry-initializer` would be an inclusion of it to other open source projects as a part of them.

**Comment by marshall-lee** [comment]
Pro-tip® for power users:

https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activesupport/lib/active_support/core_ext/object/with_options.rb

:)

Maybe it would be good idea to re-implement this thing as a mixin, not as a monkey patch.

**Comment by timriley** [comment]
I'm inclined to agree with @marshall-lee here. If duplication becomes a big concern for users of dry-initializer, and if they have ways of their own to import some code to reduce that duplication, then I think it would be best to keep the core dry-initializer API slim.

**Comment by nepalez** [comment]
@marshall-lee @timriley yes, thank you. You've convinced me to remove this method (thats why I like discussions so much).

It adds some syntax sugar, but for a high price of polluting namespace, which is unbearable for the gem pretending to be mixed in any klass.

Will remove the method in v0.10.0

**Comment by solnic** [comment]
Maybe it'd be a candidate for inclusion in dry-core? I'll have something more to say once I start working on using dry-initializer in rom-rb :)

**Comment by nepalez** [comment]
@solnic nice to hear it ;)
Would be great if you could make an issue(s) as a result of your working with the gem in rom

**Comment by nepalez** [comment]
Removed in [v0.10.0](https://github.com/dry-rb/dry-initializer/releases/tag/v0.10.0)

**Pull request closed without merging**
