### PR TITLE
improved root initializer args for ruby 3.*.* / fixed ruby deprecation

### PR DESCRIPTION
**Pull request by wwwermishel**
This's small fix is provide to use dry-initializer gem with ruby 3

### CODE REVIEW

**Comment by wwwermishel** [comment]
@flash-gordon could you please release this changes?

**Comment by flash-gordon** [comment]
dry-initializer is compatible with ruby 3. It's your code not passing values as keywords where it should have been. Ruby may make it seem like it's dry-init's fault but it isn't.

**Comment by flash-gordon** [comment]
Note that this change would break everything

**Comment by flash-gordon** [comment]
Note that this change would break everything

**Pull request closed without merging**
