### PR TITLE
Support wrapped and nested types

### PR DESCRIPTION
**Pull request by nepalez**
```ruby
class Test
  extend Dry::Initializer

  param :foo, [proc(&:to_s)]

  option :bar do
    option :baz, proc(&:to_s)
  end
end

test = Test.new(99, bar: { baz: 42 })
test.foo # => ["99"]
test.bar.baz # => "42"
```

### CODE REVIEW

**Comment by solnic** [comment]
Looks like this breaks compatbility with `rom-changeset`:

```
ArgumentError:
  The name of the argument '__data__' cannot be used for nested struct.
  A proper name can use underscores _ to divide alphanumeric parts only.
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers/build_nested_type.rb:37:in `check_name!'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers/build_nested_type.rb:16:in `call'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers.rb:89:in `block in call'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers.rb:89:in `each'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers.rb:89:in `reduce'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/dispatchers.rb:89:in `call'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/config.rb:148:in `add_definition'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer/config.rb:71:in `option'
# /Users/solnic/.gem/ruby/2.6.1/gems/dry-initializer-3.0.0/lib/dry/initializer.rb:46:in `option'
# ./lib/rom/initializer.rb:17:in `option'
```

**Comment by nepalez** [comment]
@solnic Hi
I think I know what’s going on here. But I should look at the code of 
```
./lib/rom/initializer.rb:17:in ‘option'
```

Cannot find the line in the `rom-changeset` repo

**Comment by nepalez** [comment]
@solnic I fixed this issue in `v3.0.1`
Would be nice if you could check if it works in `rom`

**Comment by solnic** [comment]
@nepalez looks like it works with `3.0.1`, thanks for addressing it so quickly 😄

**Pull request merged**
