### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by nepalez**
@flash-gordon Could you please try this branch on `rom`

I've added one option here:

```ruby
class Foo
  extend Dry::Initializer[hide_undefined: false]
  param :bar, optional: true
end

# readers are just simple `attr_accessor`-s like in v0.11
foo = Foo.new
foo.bar # => Dry::Initializer::UNDEFINED

foo = Foo.new 1
foo.bar # => 1
```

UPD: I don't sure this is a good name for the option, so you're welcome with better naming

### CODE REVIEW

**Comment by flash-gordon** [comment]
Thanks, I'll give it a shot tomorrow

**Comment by nepalez** [comment]
I give a try to "no-undefined" behavior:

```ruby
class Foo
  extend Dry::Initializer[undefined: true]
  param :bar, optional: -> { nil }
end

foo = Foo.new
foo.bar # => nil
foo.instance_variable_get :@bar # => nil
```

@flash-gordon  ^^

**Comment by flash-gordon** [comment]
this sped up tests for ~10% with no code changes, still around 50% slower than with 0.11, I will find out why
ref https://github.com/rom-rb/rom/pull/386

**Comment by nepalez** [comment]
There was one change in v1.1.0 concerning support of different ways to set a variable

```ruby
class Foo
  option :phone
  option :telephone, as: :phone
end

Foo.new(phone: "123456789").phone == Foo.new(telephone: "123456789").phone
```

To do this I needed to pre-set all values to `UNDEFINED` (or `nil`).

I'm trying to remove this in the latest commit. That's interesting whether it had a desired effect on rom.

**Comment by flash-gordon** [comment]
@nepalez it turned out that in the case of slow specs major "performance impact" is done by class-level code, that is by `Builder#call` method. This is not a big deal for ROM because normally relation classes should be defined just once and in specs we iterate over the class initialization _many_ times. I'm still wondering though _why_ it became slower, will find out soon

**Comment by flash-gordon** [comment]
@nepalez well, it's not a surprise, working with strings is slow, I gained 10% more with the following changes:
1. Reduce the number of allocations in these
```ruby
     def defaults
-      attributes.map(&:default_hash).reduce({}, :merge)
+      attributes.each_with_object({}) { |a, h| h.update(a.default_hash) }
     end

     def coercers
-      attributes.map(&:coercer_hash).reduce({}, :merge)
+      attributes.each_with_object({}) { |a, h| h.update(a.coercer_hash) }
     end
```
2. Avoid string manipulations in 
```ruby
-      <<-RUBY.gsub(/^ *\|/, "")
-        |undef_method :#{target} if method_defined?(:#{target}) ||
-        |                           protected_method_defined?(:#{target}) ||
-        |                           private_method_defined?(:#{target})
-        |#{reader_definition}
-        |#{command} :#{target}
+      <<~RUBY
+        undef_method :#{target} if method_defined?(:#{target}) ||
+                                   protected_method_defined?(:#{target}) ||
+                                   private_method_defined?(:#{target})
+        #{reader_definition}
+        #{command} :#{target}
       RUBY
```

Unfortunately the `<<~EOF` syntax is MRI 2.3+ only.

As I said it'd be great to have faster class-level definitions, but the run-time performance is much more important and this became much better once _options_ had started to include defaults.

I think I can reduce the number of `Builder#call` by using `Initializer.define`, I'll try it some time later.

Please hold on with merging this, I still need to update `rom-sql` and `rom-repo` to see if there are any outstanding issues. I hope to finish it today.

**Comment by flash-gordon** [comment]
@nepalez good news is I managed to make it work on my machine.
Bad new is there is [an issue](https://travis-ci.org/rom-rb/rom-sql/jobs/210137726) with rom-sql (and rom-repo) where MRI 2.4.0 crashes for unknown reason. I'll try to reproduce it, unfortunately Travis does not allow to ssh into the build container.

**Comment by flash-gordon** [comment]
So, this is a bug in MRI in the `Coverage` module. Ruby segfaults because of [this line](https://github.com/dry-rb/dry-initializer/blob/6b5e1f209708fbdae88960cb5063897f4bc58da2/lib/dry/initializer/builder.rb#L23). It confuses the interpreter when it tries to detect the numbers of touched lines. Once the total size of the generated code exceeds the number of lines in `builder.rb` MRI crashes.

Here's a script for reproducing the issue
```ruby
require 'coverage'
Coverage.start

require 'dry-initializer'

class Example
  extend Dry::Initializer

  40.times { |i| option :"a#{ i }" }
end

Coverage.result
```

@nepalez please, remove that `__FILE__, __LINE__ + 1` part, since it doesn't show the truth anyway we should be fine.

**Comment by nepalez** [comment]
@flash-gordon Added

Please, let me know when you're ok with using the branch in rom.

I also feeling like I need to add/refactor specs -- they become a heap of mess. However this can be done later in v1.3.1

**Comment by flash-gordon** [comment]
Yes, everything looks fine now, thank you very much for all of that. I'll merge updated dependency once you release the gem.

**Comment by flash-gordon** [comment]
ref https://bugs.ruby-lang.org/issues/13305

**Pull request merged**
