### PR TITLE
Fix Array.of constraints

### LINKED ISSUE #33: Arity check for proc to include self break dry-type arrays
Upgrading to 2.3.0 while using arrays as input types to an initializer causes issues. This appears to be related to the way `self` is called when the arity is not 0. I think the intent was to allow a proc to contain a second argument and capture self.

Here's the discussion on the forum: https://discourse.dry-rb.org/t/interaction-between-di-2-3-and-dt/380
Here's an implementation that breaks: https://github.com/kbacha/types_and_initializer_bug

You can see the arity check here: https://github.com/dry-rb/dry-initializer/blob/7a605f2a5421747f99299b610fbbc85f801d75e3/lib/dry/initializer/builders/attribute.rb#L69-L73

Which ends up passing `self` to the `method` param in dry type arrays:
https://github.com/dry-rb/dry-types/blob/506b7588a7b776cd59e2e27538256472e4c8d3df/lib/dry/types/array/member.rb#L19-L21

### PR DESCRIPTION
**Pull request by bjeanes**
Fixes #33

### CODE REVIEW

**Comment by bjeanes** [comment]
@nepalez I really don't like the spec for this but I'm not sure how to generalise the test. It's name and placement feels wrong, but hopefully it's a starting point for discussion, as it does fail without the change and pass with it.

Also, I'm not really sure what the difference between `Dry::Types::[Strict::]Array.of` and `Dry::Types.module::Array` semantically, but only the latter has an arity other than 1 (-2 in this case).

If you have any suggestions for this test, feel free to modify or to ask me to do so.

**Comment by bjeanes** [comment]
@nepalez are you still interested in this PR a requested in #33? If so, it needs to be updated slightly after reverting #46 on master, which I'm happy to do if you don't want to do so at merge time (it's pretty simple change).

**Comment by alexanderreiff** [comment]
@bjeanes @nepalez is there an opportunity for this to get merged?

**Comment by bjeanes** [comment]
It's not up to me /shrug

**Comment by jcraigk** [comment]
Just wanted to bump this old thread - it would be much appreciated if we could get this merged.

**Comment by solnic** [comment]
@bjeanes @jcraigk better late then never 😉 the fix has been merged via #71 and it's released as 3.0.3

**Pull request closed without merging**
