### PR TITLE
Fix rubocop issues

### PR DESCRIPTION
**Pull request by nepalez**
In this commit I've made several rubocop-related changes:

- fix several issues rubocop complained at
- remove unnecessary rules which **weakened** the checks
- move several metric-based checks from `.rubocop.yml` to `.rubocop-todo.yml` (via `rubocop --auto-gen-config`)

### CODE REVIEW

**Comment by nepalez** [comment]
Interesting. Jruby doesn't know how to build ruby 2.6
Could somebody from the reviewers look at the issue? Unfortunately, I have no experience with JRuby and don't really sure we should support it at all

**Comment by timriley** [comment]
@nepalez it looks like you've made direct edits to the rubocop config here - won't these be erased the next time we get changes synced from https://github.com/dry-rb/template-gem?

If we're going to do a round of rubocop-related fixes here, I think it should be done while preserving our ability to sync a common config across the dry-rb repos.

As for jruby, it looks like we don't have it in many other dry-rb CI matrices (I just checked dry-schema as an example), so I think it would be fair to remove it here.

**Comment by flash-gordon** [comment]
Everything should be synced from template-gem I think. However, this repo has a custom CI config (no clue why). In other repos I postponed support for jruby until catches up with 2.6 which is the oldest non-EOL version at the moment. I'm sure they'll get there sooner or later so I'm not worried much about it for the time being. When it comes to rubocop, I definitely prefer a unified somewhat opinionated config in template-gem. Currently, changes in this PR will be overwritten on the next commit to template-gem.

**Comment by nepalez** [comment]
Thank you, guys!
I’ll re-write the PR to use `.rubocop-todo.yml` instead of changing the common settings

**Comment by flash-gordon** [comment]
oh, I did it in master, kinda automatically. rubocop makes you a robot you know

**Pull request closed without merging**
